insert into users(name) values ('Mark');
insert into roles(role_name) values ('admin');
insert into rules(rule) values ('Rule #1');
insert into items(item_name) values ('client database');
insert into attachs(files_names) values ('db.sql');
insert into states(state) values ('ok');
insert into coments(comm_content) values ('accepted');
insert into categories(category) values ('databases');
insert into users_roles(user_id, role_id) values (1, 1);
insert into roles_rules(user_id, role_id) values (1, 1);
insert into items_users(item_id, user_id) values (1, 1);
insert into items_users(item_id, category_id) values (1, 1);
insert into items_users(item_id, state_id) values (1, 1);
insert into comments_items(comment_id, item_id) values (1, 1);
insert into attachs_items(attach_id, item_id) values (1, 1);